// Package svcconfig is the shared on-disk contract between the Blueprint
// desktop app and the Windows service binary (blueprint-svc.exe).
//
// The desktop app writes the config file when the user picks what to
// serve; the service reads it on startup and spawns llama-server
// accordingly. Both processes also use this package to read/write
// the runtime status file, which lets the Dashboard show what the
// service is doing without needing a control API call.
//
// Locations:
//
//	%ProgramData%\Blueprint\service-config.json   — desired state
//	%ProgramData%\Blueprint\service-status.json   — actual state
//	%ProgramData%\Blueprint\llama-server.log      — child stdout/stderr
//
// %ProgramData% is writable by standard users for subdirectories the
// user creates, and readable by LocalSystem (the service account),
// so app + service can share state without admin on every write.
//
// Author: Amar Mond.
package svcconfig

import (
	"encoding/json"
	"os"
	"path/filepath"
	"runtime"
)

// ServiceName is the SCM identifier. Also the service display label.
const ServiceName = "BlueprintLLM"

// ServiceDisplayName is what appears in services.msc.
const ServiceDisplayName = "Blueprint LLM Service"

// ServiceDescription is shown in the service's Properties panel.
const ServiceDescription = "Supervises a local llama-server instance so it stays up across reboots and the desktop app's exit. Managed by the Blueprint desktop app."

// Config is what the desktop app writes and the service reads.
type Config struct {
	// LlamaServerBin is the absolute path to llama-server(.exe). The
	// app populates this from runtime.Find() before writing.
	LlamaServerBin string `json:"llamaServerBin"`

	// ModelPath is the absolute path to the GGUF file to load.
	ModelPath string `json:"modelPath"`

	// ModelID + Quant are kept purely so the Dashboard can render them
	// without re-deriving from the path.
	ModelID string `json:"modelId"`
	Quant   string `json:"quant"`

	// BindHost is what llama-server's --host gets. "127.0.0.1" = local
	// only; "0.0.0.0" = LAN-visible. Configurable from the Dashboard.
	BindHost string `json:"bindHost"`

	// Port is the llama-server HTTP port.
	Port int `json:"port"`

	// APIKey is the bearer token llama-server requires. Generated by
	// the app once on first install and pinned thereafter.
	APIKey string `json:"apiKey"`

	// CtxSize is --ctx-size (max tokens).
	CtxSize int `json:"ctxSize"`

	// NGpuLayers is --n-gpu-layers (999 = offload everything).
	NGpuLayers int `json:"nGpuLayers"`

	// EnableMetrics adds --metrics so /metrics is exposed.
	EnableMetrics bool `json:"enableMetrics"`

	// MaxRestarts caps how many times the supervisor restarts a
	// crashing child before giving up. 0 = unbounded.
	MaxRestarts int `json:"maxRestarts"`

	// ─── Advanced startup params ─────────────────────────────────────
	// All zero / empty values mean "use llama.cpp's default" — the
	// supervisor only adds the flag when the value is non-zero.

	// Threads sets --threads (CPU threads). 0 = let llama.cpp pick.
	Threads int `json:"threads,omitempty"`

	// BatchSize sets --batch-size (logical max prompt batch). 0 = default.
	BatchSize int `json:"batchSize,omitempty"`

	// UBatchSize sets --ubatch-size (physical max batch). 0 = default.
	UBatchSize int `json:"uBatchSize,omitempty"`

	// FlashAttn enables --flash-attn. Faster prefill on supported GPUs.
	FlashAttn bool `json:"flashAttn,omitempty"`

	// MemoryLock pins weights in RAM with --mlock.
	MemoryLock bool `json:"memoryLock,omitempty"`

	// NoMmap disables mmap with --no-mmap (copies weights to RAM).
	NoMmap bool `json:"noMmap,omitempty"`

	// ParallelSlots sets --parallel (concurrent decode slots). 0 = 1.
	ParallelSlots int `json:"parallelSlots,omitempty"`

	// ContBatching enables --cont-batching (continuous batching across slots).
	ContBatching bool `json:"contBatching,omitempty"`

	// KvCacheTypeK sets --cache-type-k. One of "f16" | "q8_0" | "q4_0".
	// Empty = f16.
	KvCacheTypeK string `json:"kvCacheTypeK,omitempty"`

	// KvCacheTypeV sets --cache-type-v. Same options as KvCacheTypeK.
	KvCacheTypeV string `json:"kvCacheTypeV,omitempty"`

	// LogVerbose enables --verbose.
	LogVerbose bool `json:"logVerbose,omitempty"`

	// Engine selects the inference runtime. "" or "llama-cpp" = the
	// default and only currently-implemented engine. "vllm" and
	// "trt-llm" are accepted at the config level but the supervisor
	// surfaces a clear error on start until those engines ship.
	Engine string `json:"engine,omitempty"`

	// LoraAdapter is an absolute path to a .gguf LoRA adapter (or .bin
	// adapter — llama.cpp accepts both). Empty = no adapter loaded.
	// The supervisor passes --lora-scaled <path> <scale> to llama-server.
	LoraAdapter string `json:"loraAdapter,omitempty"`

	// LoraScale blends the adapter with the base. 1.0 = full adapter
	// influence (the trained behavior); 0.0 = no adapter (you may as
	// well not load it); 0.5 = halfway. 1.0 is the standard default.
	LoraScale float64 `json:"loraScale,omitempty"`

	// UpdatedAt is the unix milliseconds the app last wrote this file —
	// the service uses it to detect config changes.
	UpdatedAt int64 `json:"updatedAt"`
}

// Status is what the service writes so the Dashboard can render its
// state without needing the service to be reachable on a port.
type Status struct {
	// Phase is one of: "idle" | "starting" | "running" | "crashed" | "stopped".
	Phase string `json:"phase"`

	// ModelID + Quant of the currently-serving child.
	ModelID string `json:"modelId,omitempty"`
	Quant   string `json:"quant,omitempty"`

	// PID of the llama-server child. 0 if none.
	PID int `json:"pid,omitempty"`

	// Port the child is listening on.
	Port int `json:"port,omitempty"`

	// BindHost the child was started with.
	BindHost string `json:"bindHost,omitempty"`

	// StartedAtMs is when the current child was spawned. 0 if no child.
	StartedAtMs int64 `json:"startedAtMs,omitempty"`

	// RestartCount is how many times the supervisor has had to respawn
	// the child since service start.
	RestartCount int `json:"restartCount,omitempty"`

	// LastError is the most recent supervisor or child error, if any.
	LastError string `json:"lastError,omitempty"`

	// UpdatedAt — when the service last wrote this file.
	UpdatedAt int64 `json:"updatedAt"`
}

// DataDir is the shared directory between the desktop app (running as
// the interactive user) and the service (running as LocalSystem on
// Windows, root via systemd on Linux). Same path resolves on both
// sides so the JSON files round-trip cleanly.
//
//	BLUEPRINT_SERVICE_DATA  (env override)
//	Windows: %PROGRAMDATA%\Blueprint           (typically C:\ProgramData\Blueprint)
//	Linux:   /var/lib/blueprint                (must be world-readable)
//	macOS:   ~/.blueprint/service              (single-user only; no service on macOS yet)
func DataDir() (string, error) {
	if env := os.Getenv("BLUEPRINT_SERVICE_DATA"); env != "" {
		return env, nil
	}
	switch runtime.GOOS {
	case "windows":
		if pd := os.Getenv("PROGRAMDATA"); pd != "" {
			return filepath.Join(pd, "Blueprint"), nil
		}
		return `C:\ProgramData\Blueprint`, nil
	case "linux":
		return "/var/lib/blueprint", nil
	default:
		home, err := os.UserHomeDir()
		if err != nil {
			return "", err
		}
		return filepath.Join(home, ".blueprint", "service"), nil
	}
}

// ConfigPath returns the absolute path of service-config.json.
func ConfigPath() (string, error) {
	dir, err := DataDir()
	if err != nil {
		return "", err
	}
	return filepath.Join(dir, "service-config.json"), nil
}

// StatusPath returns the absolute path of service-status.json.
func StatusPath() (string, error) {
	dir, err := DataDir()
	if err != nil {
		return "", err
	}
	return filepath.Join(dir, "service-status.json"), nil
}

// LogPath returns the absolute path of the supervised child's log file.
func LogPath() (string, error) {
	dir, err := DataDir()
	if err != nil {
		return "", err
	}
	return filepath.Join(dir, "llama-server.log"), nil
}

// EnsureDataDir creates %ProgramData%\Blueprint if it doesn't exist.
func EnsureDataDir() error {
	dir, err := DataDir()
	if err != nil {
		return err
	}
	return os.MkdirAll(dir, 0o755)
}

// ReadConfig returns nil, nil when the file doesn't exist — the
// "service has no config yet" case.
func ReadConfig() (*Config, error) {
	path, err := ConfigPath()
	if err != nil {
		return nil, err
	}
	b, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, nil
		}
		return nil, err
	}
	var c Config
	if err := json.Unmarshal(b, &c); err != nil {
		return nil, err
	}
	return &c, nil
}

// WriteConfig saves a new desired state. Caller is expected to bump
// UpdatedAt and to stop+start the service so it picks up the change.
func WriteConfig(c Config) error {
	if err := EnsureDataDir(); err != nil {
		return err
	}
	path, err := ConfigPath()
	if err != nil {
		return err
	}
	b, err := json.MarshalIndent(c, "", "  ")
	if err != nil {
		return err
	}
	return os.WriteFile(path, b, 0o644)
}

// ReadStatus returns nil, nil when the file doesn't exist yet (service
// has never written a status, e.g. fresh install).
func ReadStatus() (*Status, error) {
	path, err := StatusPath()
	if err != nil {
		return nil, err
	}
	b, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, nil
		}
		return nil, err
	}
	var s Status
	if err := json.Unmarshal(b, &s); err != nil {
		return nil, err
	}
	return &s, nil
}

// WriteStatus is called by the service whenever the phase or PID
// changes. Best-effort — failures don't propagate.
func WriteStatus(s Status) error {
	if err := EnsureDataDir(); err != nil {
		return err
	}
	path, err := StatusPath()
	if err != nil {
		return err
	}
	b, err := json.MarshalIndent(s, "", "  ")
	if err != nil {
		return err
	}
	return os.WriteFile(path, b, 0o644)
}

// DeleteConfig removes the config file (used by Uninstall to clean up).
func DeleteConfig() error {
	path, err := ConfigPath()
	if err != nil {
		return err
	}
	err = os.Remove(path)
	if err != nil && !os.IsNotExist(err) {
		return err
	}
	return nil
}

// DeleteStatus removes the status file.
func DeleteStatus() error {
	path, err := StatusPath()
	if err != nil {
		return err
	}
	err = os.Remove(path)
	if err != nil && !os.IsNotExist(err) {
		return err
	}
	return nil
}
